### ISSUE TITLE
Error after Update to HACS 1.2.2

### ISSUE THREAD

**Issue by dhartmann84** [websylv/homeassistant-meteoswiss#20]
Unfortunately, the integration no longer works after I have updated my HACS to version 1.2.2.

`2020-07-22 19:06:27 ERROR (MainThread) [homeassistant.components.sensor] meteo-swiss: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 319, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 466, in async_device_update
    self.update  # type: ignore
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
    self._data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.7/site-packages/hamsclient/client.py", line 30, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'`

`2020-07-22 19:06:26 ERROR (SyncWorker_9) [custom_components.meteo-swiss] Unexpected error `

Thanks for your Help.

**Comment by dedors** [comment]
I just had the same error after updating home assistant to 0.113 and rebooting. After rebooting one more time the error did not come up again.

**Comment by dhartmann84** [comment]
> I just had the same error after updating home assistant to 0.113 and rebooting. After rebooting one more time the error did not come up again.

After a 3rd reboot everthing works fine. :-) Thank you!
