### ISSUE TITLE
Error loading meteo swiss on newest beta

### ISSUE THREAD

**Issue by frog32** [websylv/homeassistant-meteoswiss#15]
Since updating to 0.111.0b3 this integration seems to not load anymore.
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 319, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 472, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/meteo-swiss/sensor.py", line 105, in update
    self._data = self._client.get_data()
  File "/config/custom_components/meteo-swiss/__init__.py", line 77, in get_data
    return self._client.get_data()
  File "/usr/local/lib/python3.7/site-packages/hamsclient/client.py", line 29, in get_data
    return  {"name": self._name,"forecast": self._forecast, "condition":self._condition}
AttributeError: 'meteoSwissClient' object has no attribute '_forecast'
```

**Comment by websylv** [comment]
it's look like meteo swiss added a protection 
i look if i can find a solution

**Comment by websylv** [comment]
if you upgrade to the 1.0.1 it should be fine (I tested with the  0.112.0.dev0) and the stable 0.110.5

**Comment by braetkuegeli** [comment]
works again

**Comment by frog32** [comment]
Thank you for the quick solution here.
